### ISSUE TITLE
Remove strict versioning from requirements.txt

### ISSUE THREAD

**Issue by SergeySerj** [peterservice-rnd/robotframework-testrail#3]
Hi,

I noticed I'm unable to add this library to my project via pipenv due to 'incompatible versions in the resolved dependencies' pipenv error.
This happens because some library vendors sticks to strict versions in their requirements.txt file like this:
```
requests==2.12.4
robotframework==3.0.3
```
Therefore if one library needs `requests==2.20.0` while another library needs `requests==2.12.4` then pipenv would be unable to satisfy those conditions.
`robotframework` version is also could't be satisfied for my case as I'm using latest 3.1a2 version.

Could we have a more relaxed versions specification, like the next example?
```
requests>=2.12.4
robotframework>=3.0.3
```

**Comment by SergeySerj** [comment]
Thanks guys for quick fixes!

The more improvements I can suggest are:
1. You specify [`python_version <= '2.7'`](https://github.com/peterservice-rnd/robotframework-testrail/blob/master/requirements.txt#L1). Does it means library can't be used with Python3? It conflicts with [`'Programming Language :: Python :: 3.6',`](https://github.com/peterservice-rnd/robotframework-testrail/blob/master/setup.py#L37)
2. You specified [`requests>=2.20.0`](https://github.com/peterservice-rnd/robotframework-testrail/blob/master/requirements.txt#L2) which is fine. Can it be lowered to `requests>=2.12.4`? Some other libraries I use required lower version of `requests` library so to improve compatibility it would be good to have a lower version constraint.
3. `future==0.16.0` - can we also remove strict version specification here?

**Comment by aleskarovadi** [comment]
Hi!
Thank you for you suggestions.

1. The library can be used with Python 2.7 and Python 3. 
`python_version <= '2.7'` means that package `future==0.16.0` will be installed only when Python <= 2.7 is used. This package is not needed with Python 3.
2. It is recommended to use `requests >= 2.20.0` because earlier versions have potential security vulnerability ([more information](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2018-18074)).
3. We could remove strict version specification of `future==0.16.0`. But if the library used only with Python 3, there is no difference of how the version of this package specified.

**Comment by SergeySerj** [comment]
Thanks for the clarification @aleskarovadi!
I did not know about [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) before.
Agree, it make sense to use latest `requests` library.
Thanks.
